---
title: "Developing Data Products Course Project Pitch Presentation"
author: "Samantha Spallone"
date: "February 26, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

- This presentation is for the Developing Data Products Course Project.
- This presentation was created using Rstudio Presenter.
- The Shiny application pitched by this presentation is accessible here: http://127.0.0.1:4981/
- The Shiny application source code is available here: https://github.com/SamSpallone/Developing-Data-Products.git

## Purpose of the Shiny Application

- The Shiny application I created helps to predict the annual number of deaths in road accidents for half the US states, using number of drivers (in 10,000s) from the "road" dataset.


## More About the Dataset

The "road" dataset is a data frame with the annual deaths in road accidents for half the US states. The columns are:

- "state" --> name
- "deaths" --> number of deaths
- "drivers" --> number of drivers (in 10,000s)
- "popden" --> population density in people per square mile
- "rural" --> length of rural roads, in 1,000s of miles
- "temp" --> average daily maximum temperature in January
- "fuel" --> fuel consumption in 10,000,000 US gallons per year

Source: Imperial College, London M.Sc. exercise

## How to Use the Shiny Application

The application is simple to use. There is a slider bar for selecting the number of drivers (in 10,000s), which ranges from 11 to 952. There is also a check box to show or hide the fitted line of the model. Hit the "Submit" button to refresh the graph.

The graph shows the fitted line from the model lm(deaths ~ drivers, data = road). The predicted number of annual deaths for the selected number of drivers, based on the mode, is shown below the graph.
